#!/bin/bash

# File Update Functions
# Applies configuration changes to project files

# Updates app.config.ts with configuration
update_app_config() {
    echo -e "${YELLOW}Updating $ENV_CONFIG_FILE...${NC}"
    
    cat > "$ENV_CONFIG_FILE" << EOF
/**
 * Application Configuration
 * 
 * This file contains all project-specific configuration values.
 * Modify these values to adapt the application for different contexts.
 */

export const APP_CONFIG = {
  /**
   * Application branding and metadata
   */
  name: '$APP_NAME',
  title: '$APP_TITLE',
  description: '$APP_DESCRIPTION',
  
  /**
   * Project context and identification
   * Used for licensing, attribution, and analytics
   */
  project: {
    name: '$PROJECT_NAME',
    displayName: '$APP_TITLE',
    domain: '$PROJECT_DOMAIN',
    url: '$PROJECT_URL',
  },
  
  /**
   * Backend API configuration
   * Defines endpoints for each microservice
   */
  api: {
    auth: {
      host: '$AUTH_HOST',
      port: $AUTH_PORT,
      protocol: '$AUTH_PROTOCOL',
    },
    booking: {
      host: '$BOOKING_HOST',
      port: $BOOKING_PORT,
      protocol: '$BOOKING_PROTOCOL',
    },
    messaging: {
      host: '$MESSAGING_HOST',
      port: $MESSAGING_PORT,
      protocol: '$MESSAGING_PROTOCOL',
    },
  },
  
  /**
   * Feature flags
   * Enable/disable major application features
   */
  features: {
    auth: $FEATURE_AUTH,
    booking: $FEATURE_BOOKING,
    messaging: $FEATURE_MESSAGING,
    i18n: $FEATURE_I18N,
    policies: $FEATURE_POLICIES,
  },
  
  /**
   * UI/UX preferences
   */
  ui: {
    defaultLanguage: '$UI_DEFAULT_LANG',
    availableLanguages: ['$(echo "$UI_AVAILABLE_LANGS" | sed "s/,/', '/g")'],
    dateFormat: '$UI_DATE_FORMAT',
    timeFormat: '$UI_TIME_FORMAT',
  },
  
  /**
   * License information
   */
  license: '$PROJECT_LICENSE',
} as const;

/**
 * Helper function to construct full API URLs
 */
export function getApiUrl(service: 'auth' | 'booking' | 'messaging'): string {
  const config = APP_CONFIG.api[service];
  return \`\${config.protocol}://\${config.host}:\${config.port}\`;
}

/**
 * Export computed values for easy access
 */
export const API_BASE_URLS = {
  AUTH: getApiUrl('auth'),
  BOOKING: getApiUrl('booking'),
  MESSAGING: getApiUrl('messaging'),
} as const;
EOF
}

# Updates proxy.conf.json
update_proxy_config() {
    echo -e "${YELLOW}Updating $PROXY_CONFIG_FILE...${NC}"
    
    cat > "$PROXY_CONFIG_FILE" << EOF
{
  "/auth": {
    "target": "$AUTH_PROTOCOL://$AUTH_HOST:$AUTH_PORT",
    "secure": false,
    "changeOrigin": true,
    "pathRewrite": {
      "^/auth": "/api/auth"
    }
  },
  "/users": {
    "target": "$AUTH_PROTOCOL://$AUTH_HOST:$AUTH_PORT",
    "secure": false,
    "changeOrigin": true,
    "pathRewrite": {
      "^/users": "/api/users"
    }
  },
  "/booking": {
    "target": "$BOOKING_PROTOCOL://$BOOKING_HOST:$BOOKING_PORT",
    "secure": false,
    "changeOrigin": true,
    "pathRewrite": {
      "^/booking": "/api"
    }
  },
  "/messaging": {
    "target": "$MESSAGING_PROTOCOL://$MESSAGING_HOST:$MESSAGING_PORT",
    "secure": false,
    "changeOrigin": true,
    "pathRewrite": {
      "^/messaging": "/api"
    },
    "ws": true
  }
}
EOF
}

# Updates styles.css with custom colors and background image
update_styles() {
    [[ "$CUSTOMIZE_COLORS" != "true" ]] && [[ "$CUSTOMIZE_BACKGROUND" != "true" ]] && return
    
    echo -e "${YELLOW}Updating $STYLES_FILE with custom theme...${NC}"
    
    # Remove existing custom theme section if present
    perl -i -0pe 's/\n*\/\* Custom Theme Colors - Generated by setup script \*\/.*?^}/\n/ms' "$STYLES_FILE"
    
    # Remove trailing empty lines at the end of file
    sed -i -e :a -e '/^\s*$/d;N;ba' "$STYLES_FILE"
    
    # Build custom theme CSS
    cat >> "$STYLES_FILE" << EOF


/* Custom Theme Colors - Generated by setup script */
:root {
EOF
    
    # Add color customizations if enabled
    if [[ "$CUSTOMIZE_COLORS" == "true" ]]; then
        cat >> "$STYLES_FILE" << EOF
  --primary: $THEME_PRIMARY_COLOR;
  --secondary: $THEME_SECONDARY_COLOR;
  --danger: #ff0000;
  --text: $THEME_TEXT_COLOR;
EOF
    fi
    
    # Add background image customization if enabled
    if [[ "$CUSTOMIZE_BACKGROUND" == "true" ]]; then
        cat >> "$STYLES_FILE" << EOF
  --background-image: url('$THEME_BACKGROUND_IMAGE');
EOF
    fi
    
    # Close the :root selector
    cat >> "$STYLES_FILE" << EOF
}
EOF
}

# Updates branding icons
update_favicon() {
    [[ "$CUSTOM_FAVICON" != "true" ]] && return
    
    echo -e "${YELLOW}Updating favicon file...${NC}"
    
    # Only .ico files are supported
    # Copy to src directory
    cp "$FAVICON_PATH" "$SRC_DIR/favicon.ico"
    
    # Update index.html with the new favicon (no changes needed, just confirming path)
    # The href="/favicon.ico" in index.html already points to the correct location
    
    echo -e "${GREEN}Favicon (.ico) updated in src/ directory${NC}"
}

# Updates production.sh script
update_production_script() {
    [[ "$CONFIGURE_PRODUCTION" != "true" ]] && return
    
    echo -e "${YELLOW}Updating $PRODUCTION_SCRIPT...${NC}"
    
    cat > "$PRODUCTION_SCRIPT" << 'EOF'
#!/bin/bash

# Production Deployment Configuration
# Note: Only DOMAIN and EMAIL are customizable during setup
# PROJECT_NAME, NETWORK_NAME, and PROJECT_PATH are static values
PROJECT_NAME="PROD_CONTAINER_NAME_PLACEHOLDER"
NETWORK_NAME="PROD_NETWORK_NAME_PLACEHOLDER"
DOMAIN="PROD_DOMAIN_PLACEHOLDER"
EMAIL="PROD_EMAIL_PLACEHOLDER"
PROJECT_PATH="PROD_PROJECT_PATH_PLACEHOLDER"

source "$(dirname "$0")/dependencies.sh"
cd "$PROJECT_PATH";
docker build -t nginx .; 
docker run --name "$PROJECT_NAME" -d \
  --network "$NETWORK_NAME" \
  -p 80:80 -p 443:443 \
  -e DOMAIN="$DOMAIN" \
  -e EMAIL="$EMAIL" \
  -v /etc/letsencrypt:/etc/letsencrypt \
  nginx;
EOF

    # Replace placeholders
    sed -i "s/PROD_CONTAINER_NAME_PLACEHOLDER/$PROD_CONTAINER_NAME/g" "$PRODUCTION_SCRIPT"
    sed -i "s/PROD_NETWORK_NAME_PLACEHOLDER/$PROD_NETWORK_NAME/g" "$PRODUCTION_SCRIPT"
    sed -i "s|PROD_DOMAIN_PLACEHOLDER|$PROD_DOMAIN|g" "$PRODUCTION_SCRIPT"
    sed -i "s|PROD_EMAIL_PLACEHOLDER|$PROD_EMAIL|g" "$PRODUCTION_SCRIPT"
    sed -i "s|PROD_PROJECT_PATH_PLACEHOLDER|$PROD_PROJECT_PATH|g" "$PRODUCTION_SCRIPT"
    
    chmod +x "$PRODUCTION_SCRIPT"
}

# Updates nginx.conf with backend containers
update_nginx_config() {
    [[ "$CUSTOMIZE_BACKENDS" != "true" ]] && return
    
    echo -e "${YELLOW}Updating $NGINX_CONFIG_FILE with backend containers...${NC}"
    # This would require more complex sed/awk logic to update specific upstream blocks
    echo -e "${YELLOW}Note: Manual nginx.conf updates may be needed for backend container names${NC}"
}

# Updates entrypoint.sh certificate renewal interval
update_entrypoint_script() {
    [[ "$CONFIGURE_PRODUCTION" != "true" ]] && return
    
    echo -e "${YELLOW}Updating $ENTRYPOINT_SCRIPT...${NC}"
    # Could add custom renewal interval if configured
}

# Updates cookie constants
update_cookie_constants() {
    [[ "$CUSTOMIZE_COOKIES" != "true" ]] && return
    
    echo -e "${YELLOW}Updating cookie and storage constants...${NC}"
    
    cat > "$COOKIE_CONSTANTS_FILE" << EOF
export const COOKIE_CONSTANTS = {
  MAX_AGE: $COOKIE_MAX_AGE,
  SESSION_TIMEOUT: $SESSION_TIMEOUT,
  POLICY_MODAL_DELAY: $POLICY_MODAL_DELAY,
  CONSENT_KEY: '${STORAGE_PREFIX}consent',
  CONSENT_VALUE: 'accepted',
  CONSENT_MAX_AGE: $COOKIE_MAX_AGE
} as const;
EOF

    cat > "$STORAGE_CONSTANTS_FILE" << EOF
export const STORAGE_CONSTANTS = {
  PREFIX: '$STORAGE_PREFIX',
  TOKEN_KEY: '${STORAGE_PREFIX}token',
  TOKEN_PREFIX: 'Bearer ',
  COOKIE_TOKEN_KEY: '${STORAGE_PREFIX}token',
  COOKIE_SEPARATOR: '|'
} as const;
EOF
}

# Updates animation constants
update_animation_constants() {
    [[ "$CUSTOMIZE_ANIMATIONS" != "true" ]] && return
    
    echo -e "${YELLOW}Updating animation constants...${NC}"
    
    cat > "$ANIMATION_CONSTANTS_FILE" << EOF
export const ANIMATION_CONSTANTS = {
  TOAST_DURATION: $TOAST_DURATION,
  TYPING_SPEED: $TYPING_SPEED,
  DELAY_BETWEEN_TEXTS: $DELAY_BETWEEN_TEXTS,
  ERASING_SPEED: $TYPING_SPEED
} as const;
EOF
}

# Updates message constants
update_message_constants() {
    [[ "$CUSTOMIZE_MESSAGES" != "true" ]] && return
    
    echo -e "${YELLOW}Updating message constants...${NC}"
    
    cat > "$MESSAGES_CONSTANTS_FILE" << EOF
export const ERROR_MESSAGES = {
  NETWORK_ERROR: 'Network error occurred',
  AUTHENTICATION_FAILED: 'Authentication failed',
  INVALID_INPUT: 'Invalid input provided',
  SERVER_ERROR: 'Server error occurred',
  NOT_FOUND: 'Resource not found',
  CONVERSATION_CREATION_FAILED: 'Failed to create conversation',
  MESSAGE_SEND_FAILED: 'Failed to send message',
  SEND_MESSAGE_LOGGED_OUT: 'You must be logged in to send messages',
  LOGIN_REQUIRED: 'Please log in to continue',
  BOOKING_INCOMPLETE: 'Please complete all required fields'
} as const;

export const SUCCESS_MESSAGES = {
  LOGIN_SUCCESS: '$MSG_LOGIN_SUCCESS',
  MESSAGE_SENT: '$MSG_MESSAGE_SENT',
  BOOKING_SUCCESS: 'Booking completed successfully!'
} as const;
EOF
}

# Updates index.html title
update_index_html() {
    echo -e "${YELLOW}Updating $INDEX_FILE title...${NC}"
    sed -i "s|<title>.*</title>|<title>$APP_TITLE</title>|g" "$INDEX_FILE"
}

# Updates package.json name
update_package_json() {
    echo -e "${YELLOW}Updating $PACKAGE_FILE name...${NC}"
    local lowercase_name
    lowercase_name=$(echo "$APP_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
    
    # Use a more robust method to update package.json
    # This is a simple sed approach - consider using jq for production
    sed -i "s/\"name\": \".*\"/\"name\": \"$lowercase_name\"/g" "$PACKAGE_FILE"
}

# Applies all configuration changes
apply_configuration() {
    echo ""
    echo -e "${BLUE}Applying configuration changes...${NC}"
    echo ""
    
    update_app_config
    update_proxy_config
    update_styles
    update_favicon
    update_production_script
    update_nginx_config
    update_entrypoint_script
    update_cookie_constants
    update_animation_constants
    update_message_constants
    update_index_html
    update_package_json
    
    echo ""
    echo -e "${GREEN}All configuration files updated successfully!${NC}"
}
